### ISSUE TITLE
support both go 1.3 and go 1.4 static compilation

### ISSUE THREAD

**Issue by jonboulle** [appc/goaci#9]
goaci should be able to compile statically on both go 1.3 and go 1.4 (currently it lacks the necessary arguments for 1.4 - https://github.com/golang/go/issues/9344)

**Comment by krnowak** [comment]
That is fixed in master, so it could be closed. The only thing that doesn't work is that using installsuffix tries to install static version of std library in $GOROOT/pkg/linux_amd64_cgo (we use -installsuffix cgo), which is a problem when using go provided by a distro - usually $GOROOT is something like /usr/lib/golang, where only root has write access.

**Comment by jonboulle** [comment]
It's not actually fixed on master because #2 hasn't landed yet.

I am concerned about this -installsuffix thing, and surprised this isn't an upstream golang issue for this? Should we file one?

**Comment by krnowak** [comment]
Well, it really is fixed - https://github.com/appc/goaci/blob/master/goaci.go#L74. You probably pushed that by accident. So I rebased my changes against it and modified my fix to only remove an obsolete TODO.

And about installsuffix - https://github.com/golang/go/issues/9344#issuecomment-71288191. If you are concerned about installsuffix and permission problems then do you want me to file an issue about it? Probably a new env var GOPKG which would be for pkg directory like GOBIN for bin directory could be a solution?

**Comment by jonboulle** [comment]
> You probably pushed that by accident.

whoops :-(
I don't suppose you confirmed this still works for 1.3?

> If you are concerned about installsuffix and permission problems then do you want me to file an issue about it? 

Yes please, I would like to know what upstream thinks about this, seems like a bit of a bug to me.

**Comment by krnowak** [comment]
The installsuffix option works well for 1.3 too. @philips told me to ignore the distro-provided go for now, but I filed a bug anyway - https://github.com/golang/go/issues/10011.

I suppose I can close this one for now.

**Comment by krnowak** [comment]
A followup is here: #11.
